on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: main
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: |
          node updateManifest.mjs
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run package
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to Chrome Web Store
        if: ${{ steps.release.outputs.release_created }}
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist.zip
          extension-id: npffkekfkkdphkbleloephpjdiabicbn
          client-id: ${{ secrets.CHROME_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_STORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_STORE_REFRESH_TOKEN }}
